### PR TITLE
V14 ports

### PR DESCRIPTION
**Pull request by agritheory**

### CODE REVIEW

**Comment by HKuz** [comment]
Two things that came up in testing:
- The docs for "Company Discretionary Data" field for ACH Settings says it should show in the batch header, but I didn't see the text I used in the NACHA file (for comparison, the "ACH Description" text, which also says it goes in the batch header, showed up fine)
- I accidentally selected an on-hold invoice to pay, and rightfully got an error and the banner up top that says "This Check Run has Errors click to view". But there doesn't seem to be any way to escape out of the Check Run, fix the errors, or start a new one (it shows the "Check Run XXXX is still processing..." warning on a new Run and won't let me edit anything - which makes sense if a large run is processing, but this one will never 'submit' and escape that state). There was also a `pymysql.err.OperationalError: (1305, 'SAVEPOINT process_check_run does not exist')` error, but that seems to tie to the disabled saving in the submitting state.

**Comment by agritheory** [comment]
> I accidentally selected an on-hold invoice to pay

Ah, let me test this scenario, it should revert to draft. The API for savepoint has changed in v14, which took hours to figure out.

**Comment by agritheory** [comment]
@HKuz I believe I have fixed both issues, please review

**Review by HKuz — APPROVED** [review]
Looks good!

**Pull request merged**
