### PR TITLE
Creation of credit note on setup : bench execute 'check_run.tests.setup.before_test'

### PR DESCRIPTION
**Pull request by viralkansodiya**

### CODE REVIEW

**Comment by viralkansodiya** [comment]
@agritheory 
1 --> Credit Note Creation in setup.py
2 --> remove >0 condition to take all return entry in check run

**Comment by viralkansodiya** [comment]
@agritheory 

Hi Tyler,

I have added a code in `[setup.py](https://github.com/agritheory/check_run/blob/40389d85d3cf71da740a8d8056f25a93d3eaf077/check_run/tests/setup.py#L889)` to create a credit note against a sales invoice.

After executing bench execute 'check_run.tests.setup.before_test' , system has generating one credit note

here, I am getting 0.01 USD remain in outstanding please review below image

### Main Invoice (Overdue)

main invoice

### Return Invoice

return


When a return or credit note is created from the UI, it works perfectly. Can you suggest how to handle this conflict in test cases?

Thanks
viral kansodiya

**Comment by agritheory** [comment]
Force the precision based on the the field level precision, [like this](https://github.com/agritheory/inventory_tools/blob/6f4f63f22f3f7278e20c6aba9e5ef6a021ae03b2/inventory_tools/inventory_tools/overrides/purchase_order.py#L92)

**Comment by viralkansodiya** [comment]
@agritheory 
why every invoices has outstanding amount is same as tax amount, it should be the tax_amount + net_total

this happen after run **bench execute 'check_run.tests.setup.before_test'**

erroerin

**Comment by agritheory** [comment]
@viralkansodiya No, the only amount that is payable is what is due to the Tax Authority - in the example I think it's 6.25% of the grand total of $100.00. The $100 is a receivable to the company.

**Comment by viralkansodiya** [comment]
@agritheory you can review this PR and Merge

**Comment by agritheory** [comment]
@viralkansodiya This should be based on version 15, the changes to the PDF dependencies are not compatible.

**Comment by viralkansodiya** [comment]
> compatible

fixed

**Comment by viralkansodiya** [comment]
@agritheory should I raise this PR for version 15? or against tax_payable branch is okay

**Pull request merged**
