### PR TITLE
Amount in Check Run  as per current exchange rate 

### PR DESCRIPTION
**Pull request by viralkansodiya**
Screenshot 2024-05-10 172217

### CODE REVIEW

**Comment by viralkansodiya** [comment]
@agritheory Please check this pull request

**Comment by viralkansodiya** [comment]
Amount In Check Run --> Estimated Amount in Check Run if Non Company Currency

**Comment by viralkansodiya** [comment]
@agritheory  Please look at this image 
if company currency and `pay_to_account_currency` is different , that time lable will be change 
Amount In Check Run to Estimated Amount In Currency

conflict

**Comment by agritheory** [comment]
@viralkansodiya Can you cherry-pick these commits to the SEPA feature branch? This pull request can be closed afterwards

**Comment by viralkansodiya** [comment]
@agritheory  I have update a same code in pull request #239 , SO I am closing this pull request

**Pull request closed without merging**
