### PR TITLE
fix: serialize null transactions

### LINKED ISSUE #260: In `process_check_run`, serialize current transactions if null
This happens when the configured settings for a Check Run allow it to be processed without any other changes. 

There are a couple of events that lead to this error, and it would be better to address the root causes:
- `get_entries` is called from the browser but `frm` is not marked as dirty at this point even though the data in `transactions` has changed
- The document isn't aware that it _cannot_ be processed because there are no `transactions`

To reproduce: 
`bench reinstall --yes --admin-password admin --mariadb-root-password admin && bench execute 'check_run.tests.setup.before_test'`

Then start a new Check Run with the default company, account and bank account. 
Then "Modify Settings" and check "Pre-Select Overdue Items" and "Automatically Release On Hold Invoices"
Return to the Check Run and click "Process Check Run"

<details><summary>Stack Trace</summary>
### App Versions
```
{
	"check_run": "14.11.5",
	"erpnext": "14.70.6",
	"frappe": "14.76.2",
	"hrms": "14.28.5"
}
```
### Route
```
Form/Check Run/ACC-CR-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/check_run/check_run/check_run/doctype/check_run/check_run.py", line 939, in process_check_run
    doc.process_check_run()
  File "apps/check_run/check_run/check_run/doctype/check_run/check_run.py", line 188, in process_check_run
    for t in json.loads(self.transactions)
  File "/home/tyler/.pyenv/versions/3.10.10/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docname": "ACC-CR-2024-00001"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/check_run.check_run.doctype.check_run.check_run.process_check_run"
}
```
### Response Data
```
{
	"exception": "TypeError: the JSON object must be str, bytes or bytearray, not NoneType"
}
```
</details>

### PR DESCRIPTION
**Pull request by MyuddinKhatri**
closes #260

### CODE REVIEW

**Review by agritheory — CHANGES_REQUESTED** [review]
This solution, while technically valid leads to very poor user experience and doesn't fix the UI/UX bug that is the root problem: that the user will see a Check Run with selection, click "Process Check Run" and then receive an error message that says that they have no selected anything for payment.

I propose a solution that marks the CR as dirty when `get_entries` is called and the `transactions` field is empty:

```
function get_entries(frm) {
	return new Promise(function (resolve, reject) {
		if(!frm.doc.transactions && frm.transactions){
			frm.dirty()
		}
		resolve(window.check_run.mount(frm))
	})
}
```

This isn't ideal either, but I think it's preferable to an error message that disagrees with what the users sees.

**Review by agritheory — APPROVED** [review]

**Comment by MyuddinKhatri** [comment]
@agritheory I checked upstreams payment_entry.py, seems fine to me so updated the commit hash in our overrides.

**Review by Alchez — APPROVED** [review]

**Comment by agritheory** [comment]
@MyuddinKhatri Can you cherry-pick 60b7fc6b975fa4223359d7a3e2738520fe96b0ad onto a new version-15 based PR? You will likely have to review the overrides in that case as well.

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri Can you cherry-pick [60b7fc6](https://github.com/agritheory/check_run/commit/60b7fc6b975fa4223359d7a3e2738520fe96b0ad) onto a new version-15 based PR? You will likely have to review the overrides in that case as well.

@agritheory I have raised the PR against version-15 but track overrides is not yet setup on version-15 branch, will do it in another PR.

**Pull request merged**
