### PR TITLE
Add documentation and tests for returns

### LINKED ISSUE #124: Add tests and documentation for handling credit notes
This is an existing feature but would benefit from documentation about how to utilize it and what to expect.

### PR DESCRIPTION
**Pull request by HKuz**
Addresses #124 

- [x] Documentation: adds a screen shot and write-up for returns against purchase invoices in a Check Run
- [x] tests

### CODE REVIEW

**Comment by agritheory** [comment]
@HKuz There's a test suit branch which has some of the strategies for this

**Comment by HKuz** [comment]
@agritheory - good call. I ended up copying over the `conftest.py` file and used your tests as a base. I had to make a few tweaks to get them to pass - namely splitting up the error test and the functionality tests for both the on-hold invoice and the returns (the CR wouldn't persist after the error test), then I had to make sure only a draft CR was returned in the fixture since we're using it more than once now.

This passes when I run `pytest` locally but we'll need the CI changes plus the recent v15 test workflow updates for it to pass CI.

**Comment by agritheory** [comment]
@HKuz I think this PR is the right one to remove the cypress tests.

**Review by agritheory — APPROVED** [review]

**Comment by HKuz** [comment]
@agritheory - yup, makes sense to have the CI actually run the new tests... All set and passing 👍

**Pull request merged**
