### PR TITLE
Secondary Print Format

### LINKED ISSUE #174: Secondary Print Format
Requesting a configuration where vouchers can be printed separately from invoice details.

Example:
Using a number threshold similar to the number of invoices per voucher, have an option to print a single voucher for all invoices and a separate method for printing the invoice details if the number of invoices exceeds the threshold. This allows the check to be printed on the voucher form while regular paper is used for all the invoice details.

### PR DESCRIPTION
**Pull request by viralkansodiya**
@agritheory 
New field in **Check Run Settings** : **Secondary Print Format**

if **Secondary Print Format** is selected : payment entry will not be split by **Number of Invoices per voucher**. If in setting **Split Invoices by Address** is enable then payment entry will split by address

### CODE REVIEW

**Comment by viralkansodiya** [comment]
@agritheory  can you help me to sort-out this pre-commit problem
when I am pushing a code it's not show any error in pre-commit but on git repo it is showing a linters fail

agri

**Comment by agritheory** [comment]
@viralkansodiya This looks good, but I think we need to include a sample secondary print format. I think we can extract the existing sample format but just this section: 
image

https://github.com/agritheory/check_run/tree/version-14/check_run/check_run/print_format/example_voucher

```html
<table class="table table-responsive-sm">
				<tr><td colspan="2">{{doc.party_name}}</td>
						<td> {{ frappe.utils.formatdate(doc.reference_date) or '' }} </td>
						<td style="text-align:right;" colspan="2"> {{doc.get_formatted("base_paid_amount")}} </td>
						<tr>
							<th> Date </th>
							<th style="text-align:left;"> Reference </th>
							<th style="text-align:center;"> Amount </th>
							<th style="text-align:right;"> Payment </th>
						</tr>
					{% for reference in doc.references %}
						<tr>
						    {% if reference.reference_doctype == 'Purchase Invoice' %}
						    <td>{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_date")) or ""}}</td>
						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_no") or "" }}</td>
							{% elif reference.reference_doctype == 'Sales Invoice' %}
							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_date")) or ""}}</td>
						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_no") or "" }}</td>
						    {% elif reference.reference_doctype == 'Expense Claim' %}
							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "expense_report_date")) or "&#160;"}}</td>
						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
						    {% elif reference.reference_doctype == 'Journal Entry' %}
							<td style="text-align:left;"> {{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "posting_date")) or "&#160;"}}</td>
						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
							{% endif %}
							<td style="text-align:center;"> {{ frappe.utils.fmt_money(reference.get_formatted('total_amount'), 2, 'USD')}}</td>
							<td style="text-align:right;"> {{ reference.get_formatted('allocated_amount')}}</td>
						</tr>
					{% endfor %}
				</table>

```

**Comment by viralkansodiya** [comment]
> @viralkansodiya This looks good, but I think we need to include a sample secondary print format. I think we can extract the existing sample format but just this section: image
> 
> https://github.com/agritheory/check_run/tree/version-14/check_run/check_run/print_format/example_voucher
> 
> ```
> <table class="table table-responsive-sm">
> 				<tr><td colspan="2">{{doc.party_name}}</td>
> 						<td> {{ frappe.utils.formatdate(doc.reference_date) or '' }} </td>
> 						<td style="text-align:right;" colspan="2"> {{doc.get_formatted("base_paid_amount")}} </td>
> 						<tr>
> 							<th> Date </th>
> 							<th style="text-align:left;"> Reference </th>
> 							<th style="text-align:center;"> Amount </th>
> 							<th style="text-align:right;"> Payment </th>
> 						</tr>
> 					{% for reference in doc.references %}
> 						<tr>
> 						    {% if reference.reference_doctype == 'Purchase Invoice' %}
> 						    <td>{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_date")) or ""}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_no") or "" }}</td>
> 							{% elif reference.reference_doctype == 'Sales Invoice' %}
> 							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_date")) or ""}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_no") or "" }}</td>
> 						    {% elif reference.reference_doctype == 'Expense Claim' %}
> 							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "expense_report_date")) or "&#160;"}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
> 						    {% elif reference.reference_doctype == 'Journal Entry' %}
> 							<td style="text-align:left;"> {{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "posting_date")) or "&#160;"}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
> 							{% endif %}
> 							<td style="text-align:center;"> {{ frappe.utils.fmt_money(reference.get_formatted('total_amount'), 2, 'USD')}}</td>
> 							<td style="text-align:right;"> {{ reference.get_formatted('allocated_amount')}}</td>
> 						</tr>
> 					{% endfor %}
> 				</table>
> ```

@agritheory 
I need some clarity on this
you means I have to create new print format (secondary) there i shoud write code as mention above

**Comment by viralkansodiya** [comment]
> @viralkansodiya This looks good, but I think we need to include a sample secondary print format. I think we can extract the existing sample format but just this section: image
> 
> https://github.com/agritheory/check_run/tree/version-14/check_run/check_run/print_format/example_voucher
> 
> ```
> <table class="table table-responsive-sm">
> 				<tr><td colspan="2">{{doc.party_name}}</td>
> 						<td> {{ frappe.utils.formatdate(doc.reference_date) or '' }} </td>
> 						<td style="text-align:right;" colspan="2"> {{doc.get_formatted("base_paid_amount")}} </td>
> 						<tr>
> 							<th> Date </th>
> 							<th style="text-align:left;"> Reference </th>
> 							<th style="text-align:center;"> Amount </th>
> 							<th style="text-align:right;"> Payment </th>
> 						</tr>
> 					{% for reference in doc.references %}
> 						<tr>
> 						    {% if reference.reference_doctype == 'Purchase Invoice' %}
> 						    <td>{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_date")) or ""}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "bill_no") or "" }}</td>
> 							{% elif reference.reference_doctype == 'Sales Invoice' %}
> 							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_date")) or ""}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "po_no") or "" }}</td>
> 						    {% elif reference.reference_doctype == 'Expense Claim' %}
> 							<td style="text-align:left;">{{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "expense_report_date")) or "&#160;"}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
> 						    {% elif reference.reference_doctype == 'Journal Entry' %}
> 							<td style="text-align:left;"> {{ frappe.utils.formatdate(frappe.db.get_value(reference.reference_doctype, reference.reference_name, "posting_date")) or "&#160;"}}</td>
> 						    <td style="text-align:left;"> {{ frappe.db.get_value(reference.reference_doctype, reference.reference_name, "name") or "&#160;" }}</td>
> 							{% endif %}
> 							<td style="text-align:center;"> {{ frappe.utils.fmt_money(reference.get_formatted('total_amount'), 2, 'USD')}}</td>
> 							<td style="text-align:right;"> {{ reference.get_formatted('allocated_amount')}}</td>
> 						</tr>
> 					{% endfor %}
> 				</table>
> ```

@agritheory 

"Do you mean that in the new print format (secondary print), I should place this code as mentioned above? Or should I duplicate the existing format (example) as the secondary print and remove this code as mentioned above?"

**Comment by viralkansodiya** [comment]
@agritheory 
are you planning to use secondary print format from **Download Checks** button
agrith

**Comment by viralkansodiya** [comment]
@agritheory  Missing fields in print format

tempsnip

**Comment by agritheory** [comment]
@viralkansodiya Please review the attach PDF. 
image

Both voucher sections should use the (new) comma separated approach, which looks great. Just copy paste that please.

I don't see the secondary voucher format being generated along with this PDF (attached).
[ACC-CR-2024-0000105f9ca05f9ca.pdf](https://github.com/agritheory/check_run/files/14759670/ACC-CR-2024-0000105f9ca05f9ca.pdf)

Please rebase this branch to pick up the latest changes on branch version-14.

**Comment by viralkansodiya** [comment]
@agritheory 

[ACC-CR-2024-00002b09716.pdf](https://github.com/agritheory/check_run/files/14773447/ACC-CR-2024-00002b09716.pdf)

please review this attachment

I have added secondary print format

**Comment by viralkansodiya** [comment]
Code Changes in this PR

1) New field in Check Run Settings : Secondary Print Format
    if Secondary Print Format is selected : payment entry will not be split by Number of Invoices per voucher. If in setting Split 
    Invoices by Address is enable then payment entry will split by address
2) New Secondary print format
3) secondary print format attachment with existing attachment

**Comment by agritheory** [comment]
The latest on this combines the two formats into a single PDF, we want two PDFs, one with each format, both attached to the Check Run. The formats themselves look good, though I'm not sure if there's an extra page per-check here. That would throw off the check numbering on pre-numbered checks. 

image

[ACC-CR-2024-00001b235deb235de.pdf](https://github.com/agritheory/check_run/files/14918566/ACC-CR-2024-00001b235deb235de.pdf)

**Comment by viralkansodiya** [comment]
@agritheory 
checkrun

**Comment by viralkansodiya** [comment]
@agritheory 
All changes has been done. process to merge

**Comment by viralkansodiya** [comment]
> @agritheory checkrun

@agritheory Name of check format, which is a cheque format (Secondary Print Format)

Capture

**Pull request merged**
