### PR TITLE
Add field for Discrectionary Company Data

### PR DESCRIPTION
**Pull request by trustedcomputer**
I think I've hit all the places where this new field needs to be added. This is my first attempt at a PR, so please let me know in the discussion if there's anything I missed or if there are any suggested changes. Thanks!

### CODE REVIEW

**Comment by trustedcomputer** [comment]
@agritheory Tyler, I found a couple of json errors and have just fixed them.

**Comment by agritheory** [comment]
@put3r-r00t3r Hi Ben, sounds good. I'll take a look at it today.

**Comment by trustedcomputer** [comment]
@agritheory I have merged your PR over on my repo.

**Review by agritheory — APPROVED** [review]

**Comment by agritheory** [comment]
@put3r-r00t3r Looks good! Merged

**Pull request merged**
