### PR TITLE
Draft: Paid Invoices appearing in the Check Run

### PR DESCRIPTION
**Pull request by agritheory**
#169 

A partial but unsatisfactory solution: Payment Schedules must be populated with a valid Payment Term. This PR fixes this but I don't think it can ultimately be considered a solution because the difference here is in the detail of the config and both config styles should be respected.

### CODE REVIEW

**Comment by HKuz** [comment]
Latest push includes a working fix with minimally invasive code changes. I tweaked the PI transaction query to be a left join so any PIs that didn't have a Payment Schedule (eg the return in the test data) were still included, and re-structured the test data a bit.

After digging through the ERPNext code, I was able to re-wire our test data to fit their expectations for using/updating the Payment Schedule without changing their code. The basic issues were:

1. a Payment Term Template with more than one row (like our 18 month rental) expects each row to link to a unique Payment Term doc that specifies the exact terms (vs linking to the same Payment Term and 'manually' changing the `credit_months` field). That Payment Term is then used as part of the key to updating the Payment Schedule. Not *exactly* user-friendly for long schedule templates, but I conformed to how they do things figuring the users of Check Run are starting under those same conditions (fewer changes to ERPNext code, fewer ways to mess with their implementations 🤷  but can certainly make changes if needed)
2. For the Payment Schedule o/s amount to properly update via a Payment Entry, the Payment Term field needs to be included in the Payment Entry References table (this was addressed in the partial fix)


Manual tests:
- [x] Invoices (both payment schedule ones and not) can be paid and properly update via a Check Run. Those Invoices do not show up in a subsequent Check Run
- [x] Invoices with a Payment Schedule that are either fully or partially (one segment of many) paid via the PI -> Create -> Payment workflow won't show in a Check Run. CAVEAT: ONLY IF I made sure to select the Payment Term in the References table. If I left it blank, it would show up in a Check Run, but if I tried to pay it, the `filter_transactions` / `not_outstanding_or_cancelled` code kicked in and removed it. ERPNext attempts to auto-fill the Payment Term field, but the underlying queries don't actually get the info (further complicated if there are multiple options still o/s)

Consideration: since we're using the Payment Schedule to select PI's, we may want to put in guardrails to address the caveat in the second test above. A couple ideas:

1. add a `mandatory_depends_on` setter to that field that's triggered if `frappe.get_all("Payment Schedule", {"parent": PI_name, "outstanding": ["!=", 0.0]})` returns anything
2. include a blurb in the documentation noting the caveat

**Comment by agritheory** [comment]
> if I tried to pay it, the filter_transactions / not_outstanding_or_cancelled code kicked in and removed it. ERPNext attempts to auto-fill the Payment Term field, but the underlying queries don't actually get the info (further complicated if there are multiple options still o/s)

> Consideration: since we're using the Payment Schedule to select PI's, we may want to put in guardrails to address the caveat in the second test above. A couple ideas:

> add a mandatory_depends_on setter to that field that's triggered if frappe.get_all("Payment Schedule", {"parent": PI_name, "outstanding": ["!=", 0.0]}) returns anything

Let's implement this. We should note all the configuration nuances in the documentation.

**Comment by HKuz** [comment]
I rebased locally and had to re-pushed all commits up. Instead of a `mandatory_depends_on` for the Payment Term field, I ended up making it a validation to be able to provide more details if the field were missing. (docs are also updated with nuances)

**Comment by HKuz** [comment]
@agritheory re-tested and good to go ✅

**Pull request merged**
