### PR TITLE
Check run settings

### PR DESCRIPTION
**Pull request by agritheory**
@HKuz Can you review this? Looks like everything is working, but it could use a sanity check.
I need to redo the UI tests to create the settings. Not part of this PR.

### CODE REVIEW

**Comment by HKuz** [comment]
Functionality all looked good except a few field name/type issues when I went to download a NACHA file. The commit I sent up fixes the errors.

Other things I noticed maybe worth mentioning: 
- Expense claims: the setting works fine when I created a new claim and had the "Include Expense Claims" box checked (it showed in the Check Run list of invoices). But for some reason the test data ones wouldn't show. The only difference I could see was their status - the script-generated ones were `Submitted` where the one I created was `Unpaid`.
- UI would hang when I cancelled a check run then tried to create a new one right after. Likely no big deal as it's doing all the under-the-hood computations, but I had to refresh then stop the browser to get it to work
- UI focus - in a check run, if I try to type in the search bar, the cursor focus jumps out and goes the the first invoice's Mode of Payment field

**Comment by agritheory** [comment]
> UI focus - in a check run, if I try to type in the search bar, the cursor focus jumps out and goes the the first invoice's Mode of Payment field

@johnhkelley1 Can you take a look at this? We want to only have the keyboard listen on keystrokes if something inside the table is focused. This is out of scope of this PR, we'll probably merge this with Heather's fixes.

**Comment by agritheory** [comment]
> Expense claims: the setting works fine when I created a new claim and had the "Include Expense Claims" box checked (it showed in the Check Run list of invoices). But for some reason the test data ones wouldn't show. The only difference I could see was their status - the script-generated ones were Submitted where the one I created was Unpaid. 

@HKuz  can you look at the script to see what's going on? Alternatively we should change the query to look at docstatus ==1 and status != 'Paid'.

> UI would hang when I cancelled a check run then tried to create a new one right after. Likely no big deal as it's doing all the under-the-hood computations, but I had to refresh then stop the browser to get it to work

I'll have a look at this one, these problems are often very difficult to debug.

**Comment by agritheory** [comment]
I am merging this even with the open issues that Heather raised. The core functionality of this feature branch is complete and this will help us get the docs wrapped up too.

**Comment by HKuz** [comment]
I got the expense claim issue resolved locally (I made the tweaks in my `docs` branch, so it'll go up with my next push). Good news is it wasn't an issue with the check run code, but some missing info in the claims generated with the test script. Long story short, a `sanctioned_amount` field in the expenses table (which flows into total amounts) wasn't auto-calculating like it does in the JS form, so the `grand_total` of each form was saved as zero. The claims were filtered out of check run because they didn't have anything to pay.

@agritheory - I'll take a first crack at writing up the settings section in the docs, should get something up mid day tomorrow.

**Pull request merged**
